### ISSUE TITLE
[suggest] Rejected Suggestion issues

### ISSUE THREAD

**Issue by Grommish** [elijabesu/SauriCogs#71]
![image](https://user-images.githubusercontent.com/4427558/127266361-bc78afef-6317-49a3-b8cd-9967f4935318.png)

On `reject`ing a Suggestion, it moves it to the correct Rejected Channel and DMs the original author, but `!showsuggestion` lists it as `Approved`, and `addreason` reports it isn't Rejected.

![image](https://user-images.githubusercontent.com/4427558/127266489-4b3df184-33d3-45c0-98a2-5e78f82a4e0f.png)

![image](https://user-images.githubusercontent.com/4427558/127266571-e560d584-11c9-4c42-865e-75002ca5b952.png)

![image](https://user-images.githubusercontent.com/4427558/127266623-98a14c43-8cf3-4ef5-92b7-c4c5d90aeb04.png)

**Comment by elijabesu** [comment]
Fixed in commit linked above. If there are any issues, lmk and I'll reopen this.

**Comment by Grommish** [comment]
I updated the Cog via `cog update`, and it showed `Suggestion` was updated, however, creating a suggestion via `suggest`, marking it `reject <number>` does move it from the suggestion topic to the rejected suggestions topic.

using `addreason <number>` still shows `This suggestion hasn't been rejected.`  Using `showsuggestion` shows it `Approved` (see screenshot).  Any debugging I can help with?

![image](https://user-images.githubusercontent.com/4427558/129138146-04062d7a-a112-4342-877c-cdd2b1922f28.png)

**Comment by Grommish** [comment]
Addendum:

When I tried to do a `showsuggestion 31`, I received:

Exception in command 'showsuggestion'
Traceback (most recent call last):
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/redbot/.local/share/Red-DiscordBot/data/ninja/cogs/CogManager/cogs/suggestion/suggestion.py", line 225, in showsuggestion
    content, embed = await self._build_suggestion(
  File "/home/redbot/.local/share/Red-DiscordBot/data/ninja/cogs/CogManager/cogs/suggestion/suggestion.py", line 563, in _build_suggestion
    embed.set_author(name=atext, icon_url=op_avatar)
UnboundLocalError: local variable 'atext' referenced before assignment

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'atext' referenced before assignment
```

I unloaded and reloaded the Cog just to ensure the new code was active, No idea and might not be code-related.

**Comment by elijabesu** [comment]
Okay, I know why, I forgot I had both `approved` and `rejected` thingies for each suggestion and was only editing the `approved` one. This caused both of the issues you've described

**Comment by Grommish** [comment]
Verified fixed!  Thanks!
